[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5"
clap_complete = "4.5"
error-stack = "0.5"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = "0.3"
